Phase4
Star-Academy/Summer1400-FE-Team3 pull request #3
Opened 2021-07-31 06:58 UTC by parmida-khani

2021-07-31 09:11 UTC, sabaebrahimi requested changes

2021-07-31 09:11 UTC, sabaebrahimi commented on scripts/favorite.js
> +      '<li><a href="Song.html">' +
برای ساخت استرینگ از بک تیک و $ استفاده کنید.

2021-07-31 09:11 UTC, sabaebrahimi commented on scripts/favorite.js
> +  favArr.forEach((x) => {
<p dir="rtl">
x اصلا اسم مناسبی برای متغیر foreach نیست. می تونید از favoritItem یا مشابه اون استفاده کنید. 
</p>

2021-07-31 09:11 UTC, sabaebrahimi commented on scripts/favorite.js
> +      (x.singer.toLowerCase() === artist && x.genre.toLowerCase() === genre) ||
این رو یک تابع بکنید که مقدار بولینی برمیگردونه. وسط برنامه کثیف نباشه

2021-07-31 09:11 UTC, sabaebrahimi commented on scripts/songs.js
> +    if (x.name.toLowerCase().includes(searchValue)) {
<p dir="rtl">
همه جا x رو درست کنید
</p>

2021-07-31 09:11 UTC, sabaebrahimi commented on scripts/favorite.js
> +      favArr.forEach((song, songIndex) => {
<p dir="rtl">
این رویک تابع findIndex کنید. و این که چرا از for each معمولی استفاده نمی کنید تا وقتی به ایندکس رسید برک کنه؟
</p>

2021-07-31 09:11 UTC, sabaebrahimi commented on scripts/user.js
> +  console.log("here");
کنسول لاگ ها رو از وسط برنامه پاک کنید. برای دیباگ می تونید از دیباگر کروم استفاده کنید

2021-07-31 09:11 UTC, sabaebrahimi commented on scripts/favorite.js
> +  let artist = artistSelect.value.toLowerCase();
<p dir="rtl">
تا جایی که دیدم اینا دیگه تغییری نمی کنن بعد از مقدار دهی. از نوع const تعریف کنید.
</p>

2021-07-31 09:11 UTC, sabaebrahimi commented on scripts/favorite.js
> +let genreArr = ["all", "pop", "rock", "metal", "rap", "country"];
کانست بشه

2021-07-31 09:11 UTC, sabaebrahimi commented on scripts/favorite.js
> +      (artist.toLowerCase() === "all" && genre.toLowerCase() === "all")
<p dir="rtl">
از اونجایی که چندین جا از all استفاده کردید، استرینگش رو به صورت const  اون بالا تعریف کنین. 
</p>

2021-07-31 09:11 UTC, sabaebrahimi commented on scripts/songs.js
> +  let artist = artistSelect.value.toLowerCase();
کانست بشه

2021-07-31 09:11 UTC, sabaebrahimi commented on scripts/songs.js
> +  let searchValue = searchInput.value.toLowerCase();
این هم کانست بشه. هر جا می بینید که یه متغیری تعریف کردید که دیگه تغییر نمی کنه تغییرش بدید به کانست

2021-07-31 11:33 UTC, parmida-khani commented on scripts/favorite.js
> +      favArr.forEach((song, songIndex) => {
az forEach estefade mikardim in error ro midad search kardim in ravesho peida kardim barash... alan vali man for of ro emtehan kardam shod bejash for of gozashtam
![Screenshot (692)](https://user-images.githubusercontent.com/73592500/127738556-1d04f697-8f8f-4e04-809e-b2a1907c6749.png)

2021-07-31 11:53 UTC, sabaebrahimi commented on scripts/favorite.js
> +      favArr.forEach((song, songIndex) => {
منظور همون بود. حله

2021-08-01 19:05 UTC, heidarzade-mh approved these changes

2021-08-01 19:05 UTC, heidarzade-mh commented on scripts/favorite.js
> +let genreSelect = document.getElementById("genreSelect");
اینارو const کنید وقتی قرار نیست تغییر کنه

2021-08-01 19:05 UTC, heidarzade-mh commented on styles/scss/index.scss
> +@import "colors";
از use استفاده کنید

2021-08-01 19:05 UTC, heidarzade-mh commented on styles/scss/index.scss
> +    font-size: 2rem;
سعی کنید

2021-08-01 19:05 UTC, heidarzade-mh commented on styles/scss/index.scss
> +    font-size: 2rem;
سعی کنید عدد های ثابت رو داخل متغییر بریزید و از متغییر استفاده کنید.

2021-08-01 19:05 UTC, heidarzade-mh commented on styles/scss/signin.scss
> +@import "./colors";
از use استفاده کنید

2021-08-01 20:58 UTC, sabaebrahimi approved these changes

2021-08-02 07:34 UTC, merged